apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sharebook-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: sharebook-backend
        name: backend
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: sharebook-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
